apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-06-23T18:43:07Z"
  generateName: openebs-localpv-provisioner-8488c699fb-
  labels:
    app: openebs
    component: localpv-provisioner
    name: openebs-localpv-provisioner
    openebs.io/component-name: openebs-localpv-provisioner
    openebs.io/version: 3.6.0
    pod-template-hash: 8488c699fb
    release: openebs
  name: openebs-localpv-provisioner-8488c699fb-rxxmp
  namespace: openebs
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: openebs-localpv-provisioner-8488c699fb
    uid: dbaf2cfe-bf72-4e39-a17a-1affe76f4ef7
  resourceVersion: "4550"
  uid: 2767a071-1234-4d91-9247-6bb8f218a431
spec:
  containers:
  - args:
    - --bd-time-out=$(BDC_BD_BIND_RETRIES)
    env:
    - name: BDC_BD_BIND_RETRIES
      value: "12"
    - name: OPENEBS_NAMESPACE
      value: openebs
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: OPENEBS_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: OPENEBS_IO_ENABLE_ANALYTICS
      value: "true"
    - name: OPENEBS_IO_BASE_PATH
      value: /var/openebs/local
    - name: OPENEBS_IO_HELPER_IMAGE
      value: openebs/linux-utils:3.4.0
    - name: OPENEBS_IO_INSTALLER_TYPE
      value: charts-helm
    - name: LEADER_ELECTION_ENABLED
      value: "true"
    image: openebs/provisioner-localpv:3.4.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - test `pgrep -c "^provisioner-loc.*"` = 1
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 1
    name: openebs-localpv-provisioner
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2r9vg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: vmd38168.contaboserver.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: openebs
  serviceAccountName: openebs
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2r9vg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-06-23T18:43:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-06-24T08:34:24Z"
    message: 'containers with unready status: [openebs-localpv-provisioner]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-06-24T08:34:24Z"
    message: 'containers with unready status: [openebs-localpv-provisioner]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-06-23T18:43:24Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://147cc5c057a44a54e786a425b480e056ec2c2f1384f9e4baa289e6bc9beebdce
    image: docker.io/openebs/provisioner-localpv:3.4.0
    imageID: docker.io/openebs/provisioner-localpv@sha256:b68b8a104faa9294571b6d1b0f3c3ec15ff8ba06f6b3f8d193865f324025636a
    lastState:
      terminated:
        containerID: containerd://147cc5c057a44a54e786a425b480e056ec2c2f1384f9e4baa289e6bc9beebdce
        exitCode: 1
        finishedAt: "2023-06-24T09:15:16Z"
        reason: Error
        startedAt: "2023-06-24T09:15:16Z"
    name: openebs-localpv-provisioner
    ready: false
    restartCount: 14
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=openebs-localpv-provisioner
          pod=openebs-localpv-provisioner-8488c699fb-rxxmp_openebs(2767a071-1234-4d91-9247-6bb8f218a431)
        reason: CrashLoopBackOff
  hostIP: 207.180.253.250
  phase: Running
  podIP: 10.244.0.7
  podIPs:
  - ip: 10.244.0.7
  qosClass: BestEffort
  startTime: "2023-06-23T18:43:24Z"
