apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-01-02T17:02:39Z"
  generateName: openebs-localpv-provisioner-6b7595d4b5-
  labels:
    app: openebs
    component: localpv-provisioner
    name: openebs-localpv-provisioner
    openebs.io/component-name: openebs-localpv-provisioner
    openebs.io/version: 3.3.0
    pod-template-hash: 6b7595d4b5
    release: openebs
  name: openebs-localpv-provisioner-6b7595d4b5-znl2q
  namespace: openebs
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: openebs-localpv-provisioner-6b7595d4b5
    uid: 628c78ae-a0e8-4aa9-b66c-0146070fa679
  resourceVersion: "19243564"
  uid: 5abe7036-31a5-413b-8c9e-f0d3fc83cedb
spec:
  containers:
  - args:
    - --bd-time-out=$(BDC_BD_BIND_RETRIES)
    env:
    - name: BDC_BD_BIND_RETRIES
      value: "12"
    - name: OPENEBS_NAMESPACE
      value: openebs
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: OPENEBS_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: OPENEBS_IO_ENABLE_ANALYTICS
      value: "true"
    - name: OPENEBS_IO_BASE_PATH
      value: /var/openebs/local
    - name: OPENEBS_IO_HELPER_IMAGE
      value: openebs/linux-utils:3.3.0
    - name: OPENEBS_IO_INSTALLER_TYPE
      value: charts-helm
    - name: LEADER_ELECTION_ENABLED
      value: "true"
    image: openebs/provisioner-localpv:3.3.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - test `pgrep -c "^provisioner-loc.*"` = 1
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 1
    name: openebs-localpv-provisioner
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4pp6d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: vmd105091.contaboserver.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: openebs
  serviceAccountName: openebs
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-4pp6d
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-01-02T17:02:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-23T17:20:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-23T17:20:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-01-02T17:02:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://22db6bdb8236ec6dc4dc38e0c3a8f747e5203ae1847737da4695dce0fa233718
    image: docker.io/openebs/provisioner-localpv:3.3.0
    imageID: docker.io/openebs/provisioner-localpv@sha256:9944beedeb5ad33b1013d62da026c3ac31f29238b378335e40ded2dcfe2c56f4
    lastState:
      terminated:
        containerID: containerd://1732ae0a43eda01770083e1669f8e1b171d7859eb36ecb489dda6f224d0ed8ea
        exitCode: 255
        finishedAt: "2023-03-23T17:17:55Z"
        reason: Unknown
        startedAt: "2023-03-09T07:15:34Z"
    name: openebs-localpv-provisioner
    ready: true
    restartCount: 7
    started: true
    state:
      running:
        startedAt: "2023-03-23T17:20:29Z"
  hostIP: 89.117.56.30
  phase: Running
  podIP: 10.244.0.219
  podIPs:
  - ip: 10.244.0.219
  qosClass: BestEffort
  startTime: "2023-01-02T17:02:46Z"
